spring.application.name=educ_pltaform
server.port=8080

# Configuration de la base de données H2
spring.datasource.url=jdbc:mysql://localhost:3306/educ-db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Activer la console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB



# URL du microservice Python
python.microservice.url=http://localhost:5000/upload
# http://192.168.100.144:5000/
 # URL de l'API LLM
deepseek.api.url=https://openrouter.ai/api/v1/chat/completions
deepseek.api.key= #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



